[networks.contracts] # Defaults Contracts
weth = { abi = "abis/weth.json"}
usdc = { abi = "abis/usdc.json"}
aavev3_pool_address_provider = {abi = "abis/aavev3_pool_address_provider.json"}
pool = {abi = "abis/pool.json"}
aave_protocol_data_provider = {abi = "abis/aave_protocol_data_provider.json"}
eth_usd = {abi = "abis/eth_usd.json"}
usdc_usd = {abi = "abis/eth_usd.json"}
uniswap_swap_router = {abi = "abis/uniswap_swap_router.json"}



[networks.eth-forked]
fork = true
url = "$MAINNET_RPC_URL"
is_zksync = false
default_account_name = "anvil1"
unsafe_password_file = "$ANVIL1_PASSWORD_FILE"
chain_id = 1


[networks.eth-forked.contracts]
usdc = { address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"}  # google: usdc address eth mainnet
weth = { address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"}  # google: weth address eth mainnet
aavev3_pool_address_provider = { address = "0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e"} # doc aave -> addresses
aave_protocol_data_provider = { address = "0x497a1994c46d4f6C864904A9f1fac6328Cb7C8a6"}  # doc aave -> addresses
eth_usd = {address = "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"}  # chainlink pricefeed Ethereum MAINNET
usdc_usd = {address = "0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6"} # chainlink pricefeed Ethereum MAINNET
uniswap_swap_router = {address = "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45"} # Uniswap-> v3protocol-> technical reference-> deployments-> ethereum deployments -> SwapRouter02 address 



[networks.mainnet-tenderly] 
fork = true
url = "$TENDERLY_MAINNET_RPC_URL"
is_zksync = false
default_account_name = "anvil1"


[networks.mainnet-tenderly.contracts]
usdc = { address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"}  # google: usdc address eth mainnet
weth = { address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"}  # google: weth address eth mainnet
aavev3_pool_address_provider = { address = "0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e"} # doc aave -> addresses
aave_protocol_data_provider = { address = "0x497a1994c46d4f6C864904A9f1fac6328Cb7C8a6"}  # doc aave -> addresses
eth_usd = {address = "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"}  # chainlink pricefeed Ethereum MAINNET
usdc_usd = {address = "0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6"} # chainlink pricefeed Ethereum MAINNET
uniswap_swap_router = {address = "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45"} # Uniswap-> v3protocol-> technical reference-> deployments-> ethereum deployments -> SwapRouter02 address 







#[networks.zksync]
#url = "$ZKSYNC_RPC_URL"
#fork = true
#is_zksync = true
#explorer_uri = "https://api-era.zksync.network/api"
#explorer_type = "zksyncexplorer"
#explorer_api_key = ""
#chain_id = 324


#[networks.zksync.contracts]
#usdc = { address = ""}  # google: usdc address eth mainnet
#weth = { address = ""}  # google: weth address eth mainnet
#aavev3_pool_address_provider = { address = ""} # doc aave -> addresses
#aave_protocol_data_provider = { address = ""}  # doc aave -> addresses
#eth_usd = {address = ""}  # chainlink pricefeed Ethereum MAINNET
#usdc_usd = {address = ""} # chainlink pricefeed Ethereum MAINNET
#uniswap_swap_router = {address = ""} # Uniswap-> v3protocol-> technical 


#[networks.pyevm]
#is_zksync = false

#[networks.anvil]
#url = "http://127.0.0.1:8545"
#prompt_live = false
#save_to_db = false
#chain_id = 31337
#
#[networks.sepolia]
#url = "https://ethereum-sepolia-rpc.publicnode.com"
#chain_id = 11155111
#


# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
